---
driver:
  name: docker

provisioner:
  name: puppet_apply
  modules_path: nevermind
  resolve_with_librarian_puppet: true
  require_chef_for_busser: true

platforms:
  - name: centos-64
    driver_config:
      image: centos:6.4
      platform: centos

suites:
  - name: default
