---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: puppet_apply
  modules_path: nevermind
  resolve_with_librarian_puppet: true
  require_chef_for_busser: true

platforms:
  - name: centos6
    driver_config:
      image: jlyheden/kitchen-puppet:centos6
      platform: centos

suites:
  - name: default
